### ISSUE TITLE
Bug: Microsoft Store's account doesn't get detected

### ISSUE THREAD

**Issue by Giovix92** [pratyakshm/WinRice#36]
### WinRice version

v0.5.04112021 November Release

### Windows version

Windows 11 21H2

### Write absolute OS build version

10.0.22494.1000

### Which category is the issue related to?

Apps

### When you run WinRice, does it fail to perform a job or does it break something on your device?

WinRice fails to perform a job

### ✔️ Expected Behavior

Should find automatically the MS account in the device and installs the requested app (ex. NanaZip)

### ❌ Actual Behavior

Can't find any MS account in the device and doesn't install the requested app.

![image](https://user-images.githubusercontent.com/19226770/140662966-baf1bddd-54bd-4ae4-9c3a-7e8685161718.png)

### Steps to reproduce

Just run WinRice and let it do its job.

### PowerShell transcript output

```powershell
...
-------------------------
     APPS & FEATURES
-------------------------

Updating Visual C++ libraries...
Updated Visual C++ libraries.

Installing NanaZip... (Ctrl + Click: https://github.com/M2Team/NanaZip)
No Microsoft Store account found, failed to acquire app.

Installing HEVC Video Extensions...
Installed HEVC Video Extensions.
...
```

### Other software run

None.

**Comment by pratyakshm** [comment]
Can you please run the following in elevated terminal and show the output?
```powershell
[System.Security.Principal.WindowsIdentity]::GetCurrent().Name.split("\")[1]
```

**Comment by Giovix92** [comment]
Sure. Here you are:
```
PS C:\WINDOWS\system32> $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name.split("\")[1]
PS C:\WINDOWS\system32> Get-LocalUser $user | Where-Object { $_.Enabled -match "True"} | Where-Object { $_.PrincipalSource -match "MicrosoftAccount"}

Name     Enabled Description
----     ------- -----------
Giovix92 True
```
