### ISSUE TITLE
Show app name instead of package name

### ISSUE THREAD

**Issue by Cyberdroid1** [pratyakshm/WinRice#40]
### Select category

Windows Explorer / User Interface

### Windows version

Windows 11 21H2, Windows 10 21H2, Windows 10 21H1, Windows 10 20H2

### Expected behavior

The UI for selecting apps to uninstall should display the app name, its icon, and its package name (greyed out) instead of just package name.

### Actual behavior

The UI only shows package name 

### WinRice output

No

### Alternative software run

- [ ] I have run alternative software that offers functionality similar to WinRice

**Comment by Cyberdroid1** [comment]
Oops, I forgor 💀 there is feature request template.

**Comment by pratyakshm** [comment]
> Oops, I forgor 💀 there is feature request template.

u forgor

**Comment by Cyberdroid1** [comment]
what

**Comment by Cyberdroid1** [comment]
yes

**Comment by pratyakshm** [comment]
I've closed the issue as it is added to https://github.com/pratyakshm/WinRice/projects/4?add_cards_query=is%3Aopen. If you want to keep it open anyway, feel free to re-open.

**Comment by pratyakshm** [comment]
![image](https://user-images.githubusercontent.com/54220235/167294948-ac05d514-815e-478f-ad5c-df2ff8cc2d86.png)
Done ❤️

**Comment by Cyberdroid1** [comment]
UwU
