### ISSUE TITLE
WinRice seems to be messing up the time

### ISSUE THREAD

**Issue by CharrotParken** [pratyakshm/WinRice#42]
### Select category

Windows Explorer / User Interface

### Windows version

Windows 11 21H2

### Expected behavior

I didnt expect it to randomly change the time in the express setup

### Actual behavior

The time changed after I my pc restarted after the express setup was completed, this didnt happen the 2nd time when I manually selected the options. 

![image](https://user-images.githubusercontent.com/70406912/150626340-27289b77-a153-4be9-8bc2-d78ff270b724.png)

### WinRice output

[PowerShell_transcript.KESHAVSPC.xxJ15+LD.20220122103040.txt](https://github.com/pratyakshm/WinRice/files/7917709/PowerShell_transcript.KESHAVSPC.xxJ15%2BLD.20220122103040.txt)
[PowerShell_transcript.KESHAVSPC.NiPf_+bH.20220122161534.txt](https://github.com/pratyakshm/WinRice/files/7917710/PowerShell_transcript.KESHAVSPC.NiPf_%2BbH.20220122161534.txt)

### Alternative software run

- [ ] I have run alternative software that offers functionality similar to WinRice

**Comment by pratyakshm** [comment]
Please Windows Terminal (Admin) and run this command:
```
Remove-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\TimeZoneInformation" -Name "RealTimeIsUniversal"
```

Restart your device after running this command and let me know if this fixes your issue.

**Comment by pratyakshm** [comment]
Closing this ticket due to ignorance from author. If anyone else faces the same issue again, create a duplicate ticket.
