### ISSUE TITLE
Make "setting BIOS time to UTC" optional

### ISSUE THREAD

**Issue by Cyberdroid1** [pratyakshm/WinRice#43]
### WinRice principles

- [X] I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense.

### Explain the feature.

Currently, running WinRIce sets the BIOS to follow UTC. Many motherboards have the feature to sync the BIOS time with Windows. So, after running WinRice and rebooting, there happens to be some mix-up with the time being set, which, in the end, makes Windows display the incorrect and requires having to sync the time for settings manually. 

I would like to request to make this feature configurable.

Related to #42 

### Does your feature request involve usage of third party software?

No

### Have you written the code that adds this feature?

No

**Comment by pratyakshm** [comment]
Thanks
