### ISSUE TITLE
WinRice should check for installed software before installing

### ISSUE THREAD

**Issue by CharrotParken** [pratyakshm/WinRice#45]
### WinRice principles

- [X] I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense.

### Explain the feature.

While in express mode, winrice installs nanazip but it does that everytime you run winrice instead of just checking if it was already installed on the system. So winrice would become much faster if it just checked and ignored for nanazip instead of installing everytime. 

Also imo unpinning edge from taskbar is kinda weird...

Oh just noticed typo at the end there xd
![image](https://user-images.githubusercontent.com/70406912/152537371-d40546c7-ceb2-4df4-b3a4-6adbaff96f85.png)

### Does your feature request involve usage of third party software?

No

**Comment by pratyakshm** [comment]
Hi @CharrotParken, I fail to find where the typo is. Can you please point to it?

**Comment by CharrotParken** [comment]
@pratyakshm oh it was truest and not trust as a typo :/, oh ok nvm

**Comment by pratyakshm** [comment]
Thanks!
