### ISSUE TITLE
Settings page need some changes

### ISSUE THREAD

**Issue by mratharvasharma** [pratyakshm/WinRice#50]
### Concerned document

doc/Settings.md

### Explain the issue

Line 45 to Line 138

### Proposed changes

Unnecessary lines to be fixed.

**Comment by pratyakshm** [comment]
Hello @mratharvasharma! I have made changes to https://github.com/pratyakshm/WinRice/blob/main/doc/Settings.md. Let me know if you like it or if you think that it needs further improvements. Awaiting your feedback! 😊

**Comment by pratyakshm** [comment]
Hello @mratharvasharma! Based on feedback, I have made changes to https://github.com/pratyakshm/WinRice/blob/main/doc/Settings.md. Let me know if you like it, or if you think that it needs further improvements. Awaiting your feedback! 😊

**Comment by pratyakshm** [comment]
cc: @KenHV @LinuxPanda
