### ISSUE TITLE
WinRice didnt change Explorer's default view to "This PC"

### ISSUE THREAD

**Issue by Cyberdroid1** [pratyakshm/WinRice#52]
### Select category

Windows Explorer

### Windows version

Windows 11 22H2 (22581.200)

### Expected behavior

It should change default view to "This PC"

### Actual behavior

It did not change, and it stayed on "Quick Access"

### WinRice output
[PowerShell_transcript.LE-LAPTOP-DE-HP.SDpj16kg.20220331173826.txt](https://github.com/pratyakshm/WinRice/files/8392666/PowerShell_transcript.LE-LAPTOP-DE-HP.SDpj16kg.20220331173826.txt)

### Anything else I should know?

NA

**Comment by pratyakshm** [comment]
Fixed the issue. 
This video showcases opening File Explorer using both, the Taskbar icon and Win + E shortcut to This PC.

https://user-images.githubusercontent.com/54220235/162434281-43be533a-9ca3-41b3-9936-66ab1b9fd8b3.mp4
