### ISSUE TITLE
Don't remove "Steps Recorder" optional feature on PCs registered in WIP

### ISSUE THREAD

**Issue by Cyberdroid1** [pratyakshm/WinRice#55]
### WinRice principles

- [X] I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense.

### Explain the feature.

Do not remove the optional feature "Steps recorder" on PCs registered in WIP (insider), since it is a necessary feature when filing feedback via the Feedback Hub. 

### Does your feature request involve usage of third party software?

No

**Comment by pratyakshm** [comment]
I think that I will make WinRice no longer uninstall Steps Recorder feature in all Windows builds, including retail and pre-release, since it is an essential feature used while filing feedback. Thoughts?

**Comment by Cyberdroid1** [comment]
I was initially thinking this, sounded like a reasonable solution. But then i thought, not many people bother to file feedback. 

BUT

Only people familiar with tech would use winrice, and it seems like this audience is the one which would care to file feedback too.


Hmm, I guess keeping it regardless of the config of the PC sounds like a good option :D

**Comment by pratyakshm** [comment]
100% agreed. Will fulfill this once I get on my Windows device. Thanks for the feature request!

**Comment by pratyakshm** [comment]
Done, thanks @Cyberdroid1!
