### ISSUE TITLE
OneNote / OneNote for windows 10 isn't getting uninstalled

### ISSUE THREAD

**Issue by wanderlusttt** [pratyakshm/WinRice#61]
### Windows version

Windows 10, version 21H2 (November 2021 Update)

### Expected behavior

Uninstall OneNote

### Actual behavior

Did not uninstall OneNote

### WinRice output

[PowerShell_transcript.DESKTOP-DS2FQH3.rfhrxJ7b.20220915130305.txt](https://github.com/pratyakshm/WinRice/files/9593383/PowerShell_transcript.DESKTOP-DS2FQH3.rfhrxJ7b.20220915130305.txt)

**Comment by pratyakshm** [comment]
The log you provided says that when you run WinRice, you chose that you would select which apps you want to uninstall. You did not select to uninstall OneNote so it didn't do that. Seems like perfectly fine behavior to me.
