### ISSUE TITLE
WinRice.ps1 doesn't working properly

### ISSUE THREAD

**Issue by mrtozkn** [pratyakshm/WinRice#63]
### Windows version

Windows 10, version 21H2 (November 2021 Update)

### Expected behavior

Normal operation of WinRice.ps1

### Actual behavior

WinRice.ps1 did not work

### WinRice output

None

### Anything else I should know?

PS C:\Users\Mert Özkan\WinRice> .\WinRice.ps1
At C:\Users\Mert Özkan\WinRice\WinRice.ps1:1002 char:22
+     if (!(check($sure)) {
+                         ~
Unexpected token '{' in expression or statement.
At C:\Users\Mert Özkan\WinRice\WinRice.ps1:1002 char:22
+     if (!(check($sure)) {
+                         ~
Missing closing ')' after expression in 'if' statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by pratyakshm** [comment]
Hey there!

My bad, I pushed in-development code to main branch. But I've pulled that code back, thus the issue should be fixed now.
Please try running WinRice again and let me know how it goes!

**Comment by mrtozkn** [comment]
Hello again! 
WinRice.ps1 is now runs normally but it stucks at Installing NanaZip stage. I'm adding powershell transcription on this comment.

Thanks.


[PowerShell_transcript.DESKTOP-03TPPCG.eW+Oh15W.20221001183704.txt](https://github.com/pratyakshm/WinRice/files/9690677/PowerShell_transcript.DESKTOP-03TPPCG.eW%2BOh15W.20221001183704.txt)

**Comment by pratyakshm** [comment]
Heya! I have made a change - the installation should work properly now. Can you give it a try again and let me know? ☺️

**Comment by mrtozkn** [comment]
Hello again!
The script is working normally now. I'm closing as completed.

Thanks for all changes and for your effort.
