### ISSUE TITLE
Cannot update to Windows11 after WinRice

### ISSUE THREAD

**Issue by NiceCraftz** [pratyakshm/WinRice#64]
### Windows version

Windows 10, version 21H2 (November 2011 Update)

### Expected behavior

Could update to windows11

### Actual behavior

Can't update to windows11

### WinRice output

[PowerShell_transcript.DESKTOP-PLJQR9D.dlcNarUL.20221003223002.txt](https://github.com/pratyakshm/WinRice/files/9855244/PowerShell_transcript.DESKTOP-PLJQR9D.dlcNarUL.20221003223002.txt)

### Anything else I should know?

![image](https://user-images.githubusercontent.com/47219477/197625859-6674696f-b495-4b61-af3c-06ef8cf71506.png)
Translated is "Your organization manages the updates on this PC"

this could be because of policies that have been set on the computer by the software. any way to revert them?

**Comment by pratyakshm** [comment]
Yes. Run this command in admin Terminal:
```Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://git.io/JurY4'))```

This is mentioned in https://github.com/pratyakshm/WinRice/blob/main/doc/Individual-scripts.md.
