### ISSUE TITLE
Please add the ability to disable VBS while maintaining hyper-V functionality

### ISSUE THREAD

**Issue by gtumanyan** [pratyakshm/WinRice#65]
### WinRice principles

- [X] I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense.

### Explain the feature.

`bcdedit /set hypervisorlaunchtype off ` breaks WSL and WSA functionality

### Does your feature request involve usage of third party software?

No

**Comment by pratyakshm** [comment]
Good idea, I'm currently researching on this.

**Comment by pratyakshm** [comment]
Good idea, I'm researching about ways to do this.

**Comment by pratyakshm** [comment]
Re-opening this as I've been informed of an undocumented method to achieve this. 
Test passed in Windows 11 Build 22623.1095 Insider Beta
Will fulfill the request soon

P.S. Sorry for all the notifications

**Comment by pratyakshm** [comment]
FWIW:

![image](https://user-images.githubusercontent.com/54220235/213429923-813e7229-0b27-47a9-a98c-0cd86c853266.png)
